### ISSUE TITLE
Allow Students to login in using RPI Shibboleth/CAS

### ISSUE THREAD

**Issue by erinjordan24** [AutomaticDoorControl/AutoDoorCtrlWeb#2]
Figure out how to incorporate the RPI CAS authentication into the website to allow students to be logged in through that. Currently, we are only checking if a student's id is in our personal database with no security whatsoever. Using the RPI CAS could help make logging in more secure. May need to ask administration what information we can have access to if a login is successfu．Briefly during the final presentation someone mentioned adding the identity provider (ie. the RPI CAS system) to the main xml file or something to easily incorporate the website to our app. I personally tried to integrate the CAS system into the app using auth0, but that turned out to be a bit more difficult than expected. I would suggest looking into the xml way first before revisiting Auth0 way.

**Comment by bsakai2000** [comment]
CAS is problematic for a couple reasons, most prominently mobile clients. We're using student passwords (#22) instead for secure logins.
