### ISSUE TITLE
Incorporate Message service into actual website

### ISSUE THREAD

**Issue by erinjordan24** [AutomaticDoorControl/AutoDoorCtrlWeb#3]
So right now no message pops up upon unsuccessful login, successful logout, or successful register. I have written a message service and a message component (largely mirroring the tour of heroes Angular2 tutorial version)to address this, but never got around to integrating it with the rest of the code.

**Comment by bsakai2000** [comment]
Message service appears to be overkill for our needs. Hidden divs should be sufficient
