### ISSUE TITLE
Complaints Page

### ISSUE THREAD

**Issue by bsakai2000** [AutomaticDoorControl/AutoDoorCtrlWeb#39]
When a user navigates to /submit-complaint, they get stuck there with no links to return them to other parts of the website. We need some way (navbar, links, back button) to navigate away from /submit-complaint

**Comment by bsakai2000** [comment]
Probably the easiest way to do this is to just add the navbar into the component

```diff
index d8fac16..9677aad 100644
--- a/src/app/submit-complaint/submit-complaint.component.html
+++ b/src/app/submit-complaint/submit-complaint.component.html
@@ -1,4 +1,4 @@
-
+<app-navbar></app-navbar>
 <!--Submit form-->
 <div class="w3-row w3-padding-64">
   <h2>Where Could RPI do better?</h2>
```

**Comment by JellyWang7** [comment]
It's fixed now in the frontend branch.
