### ISSUE TITLE
**No Rush** Allow users to expire from service

### ISSUE THREAD

**Issue by erinjordan24** [AutomaticDoorControl/AutoDoorCtrlWeb#5]
Right now the only way a student is removed from the service is if they are manually deleted by an admin. I would be nice if each student had a set expiration date so they could be automatically deleted from the website. Not a thing to worry about now, but definitely for the production version since it would not be sustainable for the admins to manually delete hundreds of students at a time

**Comment by Jacob-Lane** [comment]
My only concern would be that there would inevitably be some errors, eg initial time entry, or out of sync clocks. It might be best instead to simply notify the admins or highlight the individuals that are due for removal instead of automatic deletion.

**Comment by bsakai2000** [comment]
We're not going to go this route, instead we're gonna have users reapply at the beginning of each semester (this is the same as Sodexo's MyZone model, which is similar in scope and appears to work fine). At the end of each semester, we'll clear the students db and reset for the following semester.
